name: Сообщить о проблеме
description: Для проблем, которые не подходят под другие шаблоны.
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить заявку. Этот шаблон предназначен для любых проблем, которые не подходят под другие категории.
        Для отзывов или помощи с запуском Space Station 14, пожалуйста, присоединяйтесь к нашему [Discord](https://discord.gg/YDum6bjf).
  - type: input
    attributes:
      label: Дата/Время/Сервер.
      description: Укажите дату, время и название сервера на котором случился баг. Указывайте лишь тот сервер, на которым вы были в момент бага, а не на котором думаете, что был баг.
      placeholder: 
    validations:
      required: false
  - type: textarea
    attributes:
      label: Описание
      description: |
        Четкое и краткое описание проблемы.
        Если проблема визуальная, пожалуйста, прикрепите скриншот.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Как воспроизвести (шаги)
      description: Перечислите шаги, необходимые для воспроизведения проблемы.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Дополнительная информация
      description: Добавьте сюда любой дополнительный контекст касательно проблемы. Вы можете добавить сюда скриншоты/видео/логи.
    validations:
      required: false
