- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - DSTaipan # not mappool map
  - Amber
  # - Aspid # remap in progress
  - Bagel
  - Barratry
  - Box
  - Cluster
  - Cog
  - Convex
  - Core
  - CorvaxAstra
  - CorvaxAvrite
  - CorvaxDelta
  - CorvaxPaper
  - CorvaxSilly
  - CorvaxSpectrum
  - Elkridge
  - Fland
  - Gate
  - Gemini
  - Loop
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Packed
  - Plasma
  - Reach
  - Saltern
  - Train
